[TD-13440]<fix>: move taosBenchmark out and TDinsight.sh in (#134)

diff --git a/packaging/deb/DEBIAN/postinst b/packaging/deb/DEBIAN/postinst
--- a/packaging/deb/DEBIAN/postinst
+++ b/packaging/deb/DEBIAN/postinst
@@ -9,27 +9,28 @@ if command -v sudo > /dev/null; then
 fi
 
 ${csudo} mkdir -p /usr/local/bin || :
-${csudo} ln -sf /usr/local/taos/bin/taosdump          /usr/local/bin/taosdump
-${csudo} ln -sf /usr/local/taos/bin/taosBenchmark     /usr/local/bin/taosBenchmark
-${csudo} ln -sf /usr/local/taos/bin/taosBenchmark     /usr/local/bin/taosdemo
+${csudo} ln -sf /usr/local/taos/bin/taosdump          /usr/bin/taosdump
+${csudo} ln -sf /usr/local/taos/bin/TDinsight.sh      /usr/bin/TDinsight.sh
+#${csudo} ln -sf /usr/local/taos/bin/taosBenchmark     /usr/bin/taosBenchmark
+#${csudo} ln -sf /usr/local/taos/bin/taosBenchmark     /usr/bin/taosdemo
 
-if [[ -d /usr/local/lib64 ]]; then
-    ${csudo} ln -sf /usr/local/lib/libavro.so.23.0.0 /usr/local/lib64/libavro.so.23.0.0 || :
-    ${csudo} ln -sf /usr/local/lib64/libavro.so.23.0.0 /usr/local/lib64/libavro.so.23 || :
-    ${csudo} ln -sf /usr/local/lib64/libavro.so.23 /usr/local/lib64/libavro.so || :
+#if [[ -d /usr/local/lib64 ]]; then
+#    ${csudo} ln -sf /usr/local/lib/libavro.so.23.0.0 /usr/local/lib64/libavro.so.23.0.0 || :
+#    ${csudo} ln -sf /usr/local/lib64/libavro.so.23.0.0 /usr/local/lib64/libavro.so.23 || :
+#    ${csudo} ln -sf /usr/local/lib64/libavro.so.23 /usr/local/lib64/libavro.so || :
 
-    if [ -d /etc/ld.so.conf.d ]; then
-        ${csudo} echo "/usr/local/lib64" > /etc/ld.so.conf.d/libavro.conf
-        ${csudo} ldconfig
-    else
-        echo "/etc/ld.so.conf.d not found!"
-    fi
-else
-    if [ -d /etc/ld.so.conf.d ]; then
-        ${csudo} echo "/usr/local/lib" > /etc/ld.so.conf.d/libavro.conf
-        ${csudo} ldconfig
-    else
-        echo "/etc/ld.so.conf.d not found!"
-    fi
-fi
+#    if [ -d /etc/ld.so.conf.d ]; then
+#        ${csudo} echo "/usr/local/lib64" > /etc/ld.so.conf.d/libavro.conf
+#        ${csudo} ldconfig
+#    else
+#        echo "/etc/ld.so.conf.d not found!"
+#    fi
+#else
+#    if [ -d /etc/ld.so.conf.d ]; then
+#        ${csudo} echo "/usr/local/lib" > /etc/ld.so.conf.d/libavro.conf
+#        ${csudo} ldconfig
+#    else
+#        echo "/etc/ld.so.conf.d not found!"
+#    fi
+#fi
 
