test: pacman install packages for test

diff --git a/.github/workflows/2.x-archlinux-release.yml b/.github/workflows/2.x-archlinux-release.yml
--- a/.github/workflows/2.x-archlinux-release.yml
+++ b/.github/workflows/2.x-archlinux-release.yml
@@ -75,3 +75,118 @@ jobs:
         env:
           BASE_BRANCH: ${{ github.base_ref }}
         if: github.event_name == 'pull_request'
+
+      - name: install packages for build
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          pacman -Syu --noconfirm > /dev/null
+          pacman -Sy git --noconfirm > /dev/null
+
+      - name: Checkout TDengine 2.6 branch
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        uses: actions/checkout@v2
+        with:
+          submodules: recursive
+          repository: 'taosdata/TDengine'
+          path: 'TDengine'
+          ref: '2.6'
+
+      - name: Change time zone
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          echo "disable timezone changing"
+          #timedatectl set-timezone Asia/Shanghai
+          #date
+
+      - name: Checkout TDengine's taos-tools to PR number
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+        run: |
+          cd TDengine/src/kit/taos-tools
+          git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
+          git checkout -qf FETCH_HEAD
+
+      - name: Set up Go
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.17
+
+      - name: Set up Rust
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+
+      - uses: actions/cache@v3
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        id: cache-rust
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ runner.os }}-cargo-${{ steps.setup-rust.outputs.rustc_hash }}
+
+      - name: Build & Install TDengine
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          pacman -Sy --noconfirm gcc make cmake zlib snappy gcc-libs pkg-config python3 python-pip > /dev/null
+          gcc --version
+          python3 -m pip install --upgrade pip > /dev/null 2>&1
+          cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=${{env.TOOLS_BUILD_TYPE}} -DBUILD_HTTP=false && make -j8 && make install
+          if [[ ! -f /usr/local/taos/bin/taosdump ]] || [[ ! -f /usr/local/taos/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
+
+      - name: taosdump Old Test cases
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          pip3 install numpy fabric2 psutil pandas faker toml > /dev/null 2>&1
+          pip3 install taospy > /dev/null
+
+          cd TDengine/tests/pytest
+          pkill -9 taosadapter || :
+          pkill -9 taosd || :
+
+          echo "TEST: old cases"
+          python3 ./test.py -f tools/taosdumpTest.py && echo -e "\033[32m pytest/tools/taosdumpTest.py success! \033[0m" || echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt
+
+      - name: Check Test Result
+        if: |
+          (needs.check-changed.outputs.changedflag == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          if [ -f ~/taosdump-failed.txt ]; then
+            cat ~/taosdump-failed.txt;
+            exit 1;
+          fi
