test: refine workflow output

diff --git a/.github/workflows/2.x-taosbenchmark-debug.yml b/.github/workflows/2.x-taosbenchmark-debug.yml
--- a/.github/workflows/2.x-taosbenchmark-debug.yml
+++ b/.github/workflows/2.x-taosbenchmark-debug.yml
@@ -107,12 +107,20 @@ jobs:
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
-          for i in `find taosbenchmark -name "*.py"|grep -Ev "v3"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m taosbenchmark-debug-test/$i success! \033[0m"|| echo -e "\033[31m taosbenchmark-debug-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-debug-failed.txt ;done
+          for i in `find taosbenchmark -name "*.py"|grep -Ev "v3"`;               \
+            do python3 ./test.py -f $i > /dev/null                                \
+              && echo -e "\033[32m taosbenchmark-debug-test/$i success! \033[0m"  \
+                          | tee -a ~/taosbenchmark-debug-success.txt              \
+              || echo -e "\033[31m taosbenchmark-debug-test/$i failed! \033[0m"   \
+                          | tee -a ~/taosbenchmark-debug-failed.txt ;             \
+                          done
 
       - name: Check Test Result
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          if [ -f ~/taosbenchmark-debug-failed.txt ];then
-            cat ~/taosbenchmark-debug-failed.txt;
-            exit 1;
+          if [ -f ~/taosbenchmark-debug-failed.txt ]; then
+            cat ~/taosbenchmark-debug-failed.txt
+            exit 1
+          elif [ -f ~/taosbenchmark-debug-success.txt ]; then
+            cat ~/taosbenchmark-debug-success.txt
           fi
diff --git a/.github/workflows/2.x-taosdump-release.yml b/.github/workflows/2.x-taosdump-release.yml
--- a/.github/workflows/2.x-taosdump-release.yml
+++ b/.github/workflows/2.x-taosdump-release.yml
@@ -116,11 +116,13 @@ jobs:
 
           if find tools -name "taosdump*.py"|grep -q .;
           then
-            for i in `find tools -name "taosdump*.py"`; \
-              do python3 ./test.py -f $i > /dev/null \
-                && echo -e "\033[32m $i success! \033[0m" \
-                || echo -e "\033[31m $i failed! \033[0m" \
-                            | tee -a ~/taosdump-failed.txt; done
+            for i in `find tools -name "taosdump*.py"`;       \
+              do python3 ./test.py -f $i > /dev/null          \
+                && echo -e "\033[32m $i success! \033[0m"     \
+                            | tee -a ~/taosdump-success.txt   \
+                || echo -e "\033[31m $i failed! \033[0m"      \
+                            | tee -a ~/taosdump-failed.txt;   \
+                            done
           fi
 
       - name: taosdump System Test
@@ -131,11 +133,13 @@ jobs:
           sudo pkill -9 taosd || :
           if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; \
-              do python3 ./test.py -f $i > /dev/null \
+            for i in `find 5-taos-tools/taosdump -name "*.py"`;       \
+              do python3 ./test.py -f $i > /dev/null                  \
                 && echo -e "\033[32m system-test/$i success! \033[0m" \
-                || echo -e "\033[31m system-test/$i failed! \033[0m" \
-                            | tee -a ~/taosdump-failed.txt; done
+                            | tee -a ~/taosdump-success.txt           \
+                || echo -e "\033[31m system-test/$i failed! \033[0m"  \
+                            | tee -a ~/taosdump-failed.txt;           \
+                            done
           fi
 
       - name: taosdump Old Test
@@ -145,8 +149,9 @@ jobs:
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
           python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null \
-            && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m" \
-            || echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m" \
+            && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"  \
+                            | tee -a ~/taosdump-success.txt                               \
+            || echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"    \
                             | tee -a ~/taosdump-failed.txt
 
       - name: taosdump Develop Test
@@ -159,10 +164,12 @@ jobs:
           if find taosdump/native -name "*.py"|grep -q .;
           then
             for i in `find taosdump/native -name "*.py"`; \
-              do python3 ./test.py -f $i > /dev/null \
-                && echo -e "\033[32m develop-test/$i success! \033[0m" \
-                || echo -e "\033[31m develop-test/$i failed! \033[0m" \
-                            | tee -a ~/taosdump-failed.txt ;done
+              do python3 ./test.py -f $i > /dev/null                    \
+                && echo -e "\033[32m develop-test/$i success! \033[0m"  \
+                            | tee -a ~/taosdump-success.txt             \
+                || echo -e "\033[31m develop-test/$i failed! \033[0m"   \
+                            | tee -a ~/taosdump-failed.txt ;            \
+                            done
           fi
 
       - name: taosdump special Develop Test
@@ -174,17 +181,21 @@ jobs:
 
           if find taosdump/native2 -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/native2 -name "*.py"`; \
-              do python3 ./test.py -f $i > /dev/null \
-                && echo -e "\033[32m $i success! \033[0m" \
-                || echo -e "\033[31m $i failed! \033[0m" \
-                            | tee -a ~/taosdump-failed.txt ;done
+            for i in `find taosdump/native2 -name "*.py"`;    \
+              do python3 ./test.py -f $i > /dev/null          \
+                && echo -e "\033[32m $i success! \033[0m"     \
+                            | tee -a ~/taosdump-success.txt   \
+                || echo -e "\033[31m $i failed! \033[0m"      \
+                            | tee -a ~/taosdump-failed.txt;   \
+                            done
           fi
 
       - name: Check Test Result
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          if [ -f ~/taosdump-failed.txt ];then
-            cat ~/taosdump-failed.txt;
-            exit 1;
+          if [ -f ~/taosdump-failed.txt ]; then
+            cat ~/taosdump-failed.txt
+            exit 1
+          elif [ -f ~/taosdump-success.txt ]; then
+            cat ~/taosdump-success.txt
           fi
diff --git a/.github/workflows/3.0-taosbenchmark-debug.yml b/.github/workflows/3.0-taosbenchmark-debug.yml
--- a/.github/workflows/3.0-taosbenchmark-debug.yml
+++ b/.github/workflows/3.0-taosbenchmark-debug.yml
@@ -164,7 +164,13 @@ jobs:
 
           if find taosbenchmark -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark -name "*.py"|grep -Ev "v2|websocket|taosdemo|kill-slow-query|cloud"|sort`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m taosbenchmark-release-test/$i success! \033[0m"|| echo -e " \033[31m taosbenchmark-release-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-release-failed.txt; done
+            for i in `find taosbenchmark -name "*.py"|grep -Ev "v2|websocket|taosdemo|kill-slow-query|cloud"|sort`; \
+              do printf $i && python3 ./test.py -f $i > /dev/null                     \
+                && echo -e " \033[32m taosbenchmark-release-test/$i success! \033[0m" \
+                          | tee -a ~/taosbenchmark-release-success.txt                \
+                || echo -e " \033[31m taosbenchmark-release-test/$i failed! \033[0m"  \
+                          | tee -a ~/taosbenchmark-release-failed.txt;                \
+                          done
           fi
 
       - name: Run cloud test cases
@@ -179,7 +185,13 @@ jobs:
 
           if find taosbenchmark/v3 -name "cloud*.py"|grep -q .;
           then
-            for i in `find taosbenchmark/v3 -name "cloud*.py"`; do printf $i && python3 ./test.py -f $i && echo -e " \033[32m benchmark-cloud-test:$i success! \033[0m"|| echo -e " \033[31m benchmark-cloud-test:$i failed! \033[0m" | tee -a ~/taosbenchmark-cloud-failed.txt; done
+            for i in `find taosbenchmark/v3 -name "cloud*.py"`; \
+              do printf $i && python3 ./test.py -f $i \
+                && echo -e " \033[32m benchmark-cloud-test:$i success! \033[0m" \
+                          | tee -a ~/taosbenchmark-cloud-success.txt            \
+                || echo -e " \033[31m benchmark-cloud-test:$i failed! \033[0m"  \
+                          | tee -a ~/taosbenchmark-cloud-failed.txt;            \
+                          done
           fi
 
       - name: Test WebSocket cases
@@ -192,7 +204,13 @@ jobs:
 
           if find taosbenchmark/v3 -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark/v3 -name "websocket*.py"`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m benchmark-ws-test:$i success! \033[0m"|| echo -e " \033[31m benchmark-ws-test:$i failed! \033[0m" | tee -a ~/taosbenchmark-ws-failed.txt; done
+            for i in `find taosbenchmark/v3 -name "websocket*.py"`; \
+              do printf $i && python3 ./test.py -f $i > /dev/null   \
+                && echo -e " \033[32m benchmark-ws-test:$i success! \033[0m"  \
+                          | tee -a ~/taosbenchmark-ws-success.txt             \
+                || echo -e " \033[31m benchmark-ws-test:$i failed! \033[0m"   \
+                          | tee -a ~/taosbenchmark-ws-failed.txt;             \
+                          done
           fi
 
       - name: Test taosdemo query
@@ -205,7 +223,13 @@ jobs:
 
           if find taosbenchmark -name "taosdemo*.py"|grep -Ev "v2"|grep -q .;
           then
-            for i in `find taosbenchmark -name "taosdemo*.py"|grep -Ev "v2"`; do printf $i && python3 ./test.py -f $i && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosbenchmark-release-failed.txt; done
+            for i in `find taosbenchmark -name "taosdemo*.py"|grep -Ev "v2"`;   \
+              do printf $i && python3 ./test.py -f $i                           \
+                && echo -e "\033[32m $i success! \033[0m"                       \
+                  | tee -a ~/taosbenchmark-release-success.txt                  \
+                || echo -e "\033[31m $i failed! \033[0m"                        \
+                  | tee -a ~/taosbenchmark-release-failed.txt;                  \
+              done
           fi
 
       - name: 'Upload taosd logs'
@@ -221,17 +245,23 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          if [ -f ~/taosbenchmark-release-failed.txt ];then
+          if [ -f ~/taosbenchmark-release-failed.txt ]; then
             cat ~/taosbenchmark-release-failed.txt
             exit 1
+          elif [ -f ~/taosbenchmark-release-success.txt ]; then
+            cat ~/taosbenchmark-release-success.txt
           fi
 
-          if [ -f ~/taosbenchmark-cloud-failed.txt ];then
+          if [ -f ~/taosbenchmark-cloud-failed.txt ]; then
             cat ~/taosbenchmark-cloud-failed.txt
             exit 1
+          elif [ -f ~/taosbenchmark-cloud-success.txt ]; then
+            cat ~/taosbenchmark-cloud-success.txt
           fi
 
-          if [ -f ~/taosbenchmark-ws-failed.txt ];then
+          if [ -f ~/taosbenchmark-ws-failed.txt ]; then
             cat ~/taosbenchmark-ws-failed.txt
             exit 1
+          elif [ -f ~/taosbenchmark-ws-success.txt ]; then
+            cat ~/taosbenchmark-ws-success.txt
           fi
diff --git a/.github/workflows/3.0-taosdump-debug.yml b/.github/workflows/3.0-taosdump-debug.yml
--- a/.github/workflows/3.0-taosdump-debug.yml
+++ b/.github/workflows/3.0-taosdump-debug.yml
@@ -152,9 +152,21 @@ jobs:
           sudo pkill -9 taosd || :
 
           echo "TEST: old cases"
-          python3 ./test.py -f taosdump/old/taosdumpTest.py > /dev/null && echo -e "\033[32m taosdumpTest.py success! \033[0m"|| echo -e "\033[31m taosdumpTest.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f taosdump/old/taosdumpTest2.py > /dev/null && echo -e "\033[32m taosdumpTest2.py success! \033[0m"|| echo -e "\033[31m taosdumpTest2.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f taosdump/old/taosdumpTestNanoSupport.py > /dev/null && echo -e "\033[32m taosdumpTestNanoSupport.py success! \033[0m"|| echo -e "\033[31m taosdumpTestNanoSupport.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
+          python3 ./test.py -f taosdump/old/taosdumpTest.py > /dev/null   \
+            && echo -e "\033[32m taosdumpTest.py success! \033[0m"        \
+                      | tee -a ~/taosdump-success.txt                     \
+            || echo -e "\033[31m taosdumpTest.py failed! \033[0m"         \
+                      | tee -a ~/taosdump-failed.txt
+          python3 ./test.py -f taosdump/old/taosdumpTest2.py > /dev/null  \
+            && echo -e "\033[32m taosdumpTest2.py success! \033[0m"       \
+                        | tee -a ~/taosdump-success.txt                   \
+            || echo -e "\033[31m taosdumpTest2.py failed! \033[0m"        \
+                        | tee -a ~/taosdump-failed.txt
+          python3 ./test.py -f taosdump/old/taosdumpTestNanoSupport.py > /dev/null \
+            && echo -e "\033[32m taosdumpTestNanoSupport.py success! \033[0m"     \
+                        | tee -a ~/taosdump-success.txt                           \
+            || echo -e "\033[31m taosdumpTestNanoSupport.py failed! \033[0m"      \
+                        | tee -a ~/taosdump-failed.txt
 
 
       - name: taosdump Develop Test
@@ -171,10 +183,20 @@ jobs:
           echo "TEST: develop test cases"
           if find taosdump/native -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/native -name "*.py" | grep -Ev "Float|Double"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+            for i in `find taosdump/native -name "*.py" | grep -Ev "Float|Double"`; \
+              do python3 ./test.py -f $i > /dev/null        \
+                && echo -e "\033[32m $i success! \033[0m"   \
+                          | tee -a ~/taosdump-success.txt   \
+                || echo -e "\033[31m $i failed! \033[0m"    \
+                          | tee -a ~/taosdump-failed.txt;   \
+                          done
           fi
 
-          for i in `find taosdump/native -name "*.py" | grep "Float|Double"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+          for i in `find taosdump/native -name "*.py" | grep "Float|Double"`; \
+            do python3 ./test.py -f $i > /dev/null          \
+              && echo -e "\033[32m $i success! \033[0m"     \
+              || echo -e "\033[31m $i failed! \033[0m" ;    \
+                          done
 
       - name: Check Test Result
         if:
@@ -182,7 +204,9 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          if [ -f ~/taosdump-failed.txt ];then
+          if [ -f ~/taosdump-failed.txt ]; then
             cat ~/taosdump-failed.txt;
             exit 1;
+          elif [ -f ~/taosdump-success.txt ]; then
+            cat ~/taosdump-success.txt
           fi
diff --git a/.github/workflows/3.0-taosdump-release-ws.yml b/.github/workflows/3.0-taosdump-release-ws.yml
--- a/.github/workflows/3.0-taosdump-release-ws.yml
+++ b/.github/workflows/3.0-taosdump-release-ws.yml
@@ -188,7 +188,13 @@ jobs:
 
           if find taosdump/ws3 -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/ws3 -name "*.py"|grep -Ev "Float|Double"`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m develop-test:$i success! \033[0m"|| echo -e " \033[31m develop-test:$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+            for i in `find taosdump/ws3 -name "*.py"|grep -Ev "Float|Double"`;  \
+              do printf $i && python3 ./test.py -f $i > /dev/null               \
+                && echo -e " \033[32m develop-test:$i success! \033[0m"         \
+                            | tee -a ~/taosdump-success.txt                     \
+                || echo -e " \033[31m develop-test:$i failed! \033[0m"          \
+                            | tee -a ~/taosdump-failed.txt ;                    \
+                            done
           fi
 
       - name: taosdump Cmd line Test
@@ -208,7 +214,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          if [ -f ~/taosdump-failed.txt ];then
+          if [ -f ~/taosdump-failed.txt ]; then
             if [ -f ~/taosa.log ]; then
               cat ~/taosa.log
             else
@@ -218,4 +224,6 @@ jobs:
             cat ~/taosdump-failed.txt
 
             exit 1
+          elif [ -f ~/taosdump-success.txt ]; then
+            cat ~/taosdump-success.txt
           fi
