test: temporary debug

diff --git a/.github/workflows/3.0-taosdump-release.yml b/.github/workflows/3.0-taosdump-release.yml
--- a/.github/workflows/3.0-taosdump-release.yml
+++ b/.github/workflows/3.0-taosdump-release.yml
@@ -122,23 +122,23 @@ jobs:
             for i in `find tools -name "taosdump*.py"`; do python3 ./test.py -f $i && echo -e "\033[32m $i success! \033[0m" || echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
           fi
 
-      - name: taosdump System Test
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-          then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
-          fi
+          #      - name: taosdump System Test
+          #if: steps.changed-files-specific.outputs.any_changed == 'true'
+          #run: |
+          #cd TDengine/tests/system-test
+          #sudo pkill -9 taosadapter || :
+          #sudo pkill -9 taosd || :
+          #if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          #then
+          #  for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
+          #fi
 
-      - name: taosdump Old Test
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
+          #- name: taosdump Old Test
+          #if: steps.changed-files-specific.outputs.any_changed == 'true'
+          #run: |
+          #cd TDengine/tests/system-test
+          #sudo pkill -9 taosadapter || :
+          #sudo pkill -9 taosd || :
             #          python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
 
       - name: taosdump Develop Test
