test: taosdump functest suppliment (#328)
* test: refine tests for taosdump

* test: rm tests/CMakeLists.txt

* test: change workflow accordingly

* fix: taosdump ws float null

* test: coveralls.yml includes websocket test

* fix: disable taosdump/ws dep

* fix: wrong filename in cmake file

* test: add more test cases

* test: add expect test taosdump password

* fix: ci-taosdump-release-ws.yml wrong branch

* test: cherry pick from other branch

* test: add tools path finding for 3.0

* test: remove days/blocks for 3.0

* fix: .github/workflows/non-x64.yml

* test: add vnodes=256 env variable for 3.0

* test: fix windows-build-for3.0.yml

* test: disable ws for tdengine 2.0

* test: disable ws for tdengine 2.0 on centos

* fix: windows compile

* fix: check windows macro

* test: use test/sangshuduo/TD-17080-taosdump-functest on windows build

* fix: pip3 install taospy on centos

* test: add 3.0-coveralls.yml

* fix: replace test branch with 3.0

* fix: add expect install

* fix: stb pointer is null on tdengine 3.0

* test: add basic test cases

* fix: use ins_ instead of user_

* fix: select tbname,stbname from schema

* test: remove taosdump3.py

* test: add ws3 test

* test: remove nested query case

* test: remove taosdemo old test case

* fix: refine coverage test

* test: use test/sangshuduo/TD-17080-taosdump-functest

* test: disable taosdump test col tag case

Co-authored-by: Yang Zhao <yzhao@taosdata.com>

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -1,4 +1,4 @@
-name: Coveralls (2.x)
+name: Coveralls (3.0)
 on:
   push:
     branches: [ develop ]
@@ -60,14 +60,13 @@ jobs:
         run: |
           echo "One or more files listed above has changed."
 
-      - name: Checkout tdengine
+      - name: Checkout TDengine
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         uses: actions/checkout@v2
         with:
-          submodules: recursive
           repository: 'taosdata/TDengine'
           path: 'TDengine'
-          ref: 'develop'
+          ref: 'test/sangshuduo/TD-17080-taosdump-functest'
 
       - name: Change time zone
         if: steps.changed-files-specific.outputs.any_changed == 'true'
@@ -85,26 +84,6 @@ jobs:
           #  || echo "${{ github.head_ref }} not found in TDengine"
 
           #if: github.event_name == 'pull_request'
-
-      - name: Install packages
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: sudo apt-get install lzma-dev liblzma-dev libjansson-dev libz-dev libsnappy-dev pkg-config lcov expect -y > /dev/null
-
-      - name: Checkout TDengine's taos-tools to develop latest
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/src/kit/taos-tools
-          git checkout develop
-          git pull
-
-      - name: Checkout TDengine's taos-tools to PR number
-        if: |
-          github.event_name == 'pull_request' &&
-          steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/src/kit/taos-tools
-          git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
-          git checkout -qf FETCH_HEAD
 
       - name: Set up Go
         if: steps.changed-files-specific.outputs.any_changed == 'true'
@@ -128,14 +107,55 @@ jobs:
             ~/.cargo/git/db/
           key: ${{ runner.os }}-cargo-${{ steps.setup-rust.outputs.rustc_hash }}
 
+      - uses: actions/cache@v3
+        id: cache-rust-target
+        with:
+          path: |
+            TDengine/tools/taosws-rs/target/
+          key: ${{ runner.os }}-cargo-target-${{ steps.setup-rust.outputs.rustc_hash }}
+
+      - name: cmake first TDengine
+        if: |
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          sudo apt update -y > /dev/null
+          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y > /dev/null
+          cd TDengine
+          mkdir debug
+          cd debug
+          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true -DTOOLS_COVER=true > /dev/null
+          make -j8 > /dev/null
+
+      - name: show TDengine's taosws commit
+        if: |
+          steps.changed-files-specific.outputs.any_changed == 'true' &&
+          github.event_name == 'pull_request'
+        run: |
+          cd TDengine/tools/taosws-rs
+          git log --oneline | head -1
+
+      - name: Install packages
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        run: sudo apt-get install lzma-dev liblzma-dev libjansson-dev libz-dev libsnappy-dev pkg-config lcov expect -y > /dev/null
+
+      - name: Checkout TDengine's taos-tools to PR number
+        if: |
+          github.event_name == 'pull_request' &&
+          steps.changed-files-specific.outputs.any_changed == 'true'
+        run: |
+          cd TDengine/tools/taos-tools
+          git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
+          git checkout -qf FETCH_HEAD
+
       - name: Build & Install TDengine
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine
-          mkdir debug
+          mkdir debug ||:
           cd debug
-          cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DBUILD_TOOLS=true -DTOOLS_COVER=true -DTOOLS_BUILD_TYPE=Debug > /dev/null 2>&1
-          make > /dev/null 2>&1
+          make -j8 > /dev/null
           sudo make install > /dev/null
           if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
           then
@@ -149,7 +169,7 @@ jobs:
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           echo "TEST: taodump -p"
-          cd TDengine/src/kit/taos-tools/tests/taosdump
+          cd TDengine/tools/taos-tools/tests/taosdump
           ./exp.sh
 
       - name: Basic Test
@@ -175,7 +195,7 @@ jobs:
           echo "TEST: taodump --databases -h localhost -u root"
           ./build/bin/taosdump --databases -h localhost -u root > /dev/null 2>&1 || :
 
-          nohup sudo taosd > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
           sleep 10
 
           # test codec
@@ -304,7 +324,7 @@ jobs:
           cd TDengine/debug
           echo "TEST: dump old format data in"
           ./build/bin/taos -s "drop database test"
-          tar xvJf ../src/kit/taos-tools/example-data/example-data.tar.xz -C .
+          tar xvJf ../tools/taos-tools/example-data/example-data.tar.xz -C .
           ./build/bin/taosdump -i dump -gg
           rm -f *.sql *.avro*
 
@@ -318,15 +338,14 @@ jobs:
           echo "TEST: old cases"
           python3 ./test.py -f tools/taosdumpTest.py > /dev/null
           python3 ./test.py -f tools/taosdumpTest2.py > /dev/null
-          python3 ./test.py -f tools/taosdumpTest3.py > /dev/null
           python3 ./test.py -f tools/taosdumpTestNanoSupport.py > /dev/null
-          python3 test.py -f query/nestedQuery/nestedQuery.py > /dev/null
-          python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null
+          #python3 test.py -f query/nestedQuery/nestedQuery.py > /dev/null
+          #python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null
 
       - name: taosdump native Develop Test
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          cd TDengine/src/kit/taos-tools/tests
+          cd TDengine/tools/taos-tools/tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -337,17 +356,17 @@ jobs:
             for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
-          #      - name: taosdump WebSocket Develop Test
-          #if: steps.changed-files-specific.outputs.any_changed == 'true'
-          #run: |
-          #cd TDengine/src/kit/taos-tools/tests
-          #sudo pkill -9 taosadapter || :
-          #sudo pkill -9 taosd || :
+      - name: taosdump WebSocket Develop Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        run: |
+          cd TDengine/tools/taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
 
-          #if find taosdump/ws -name "*.py"|grep -q .;
-          #then
-          #  for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
-          #fi
+          if find taosdump/ws3 -name "*.py"|grep -q .;
+          then
+            for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+          fi
 
       - name: System Test cases
         if: steps.changed-files-specific.outputs.any_changed == 'true'
@@ -356,7 +375,7 @@ jobs:
           echo "TEST: system test cases"
           if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find 5-taos-tools/taosdump -name "*.py"|grep -v taosdumpTestColTag`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
           python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"
@@ -379,17 +398,17 @@ jobs:
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           topdir=`pwd`
-          cd TDengine/debug/src/kit/taos-tools
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
+          cd TDengine/debug/tools/taos-tools
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
+          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
           mkdir ${topdir}/coverage || :
           lcov -c -d . -o ${topdir}/coverage/lcov-with-deps.info
           lcov -r ${topdir}/coverage/lcov-with-deps.info "*/deps/*" -o ${topdir}/coverage/lcov.info
