fix: taosdump wstimeout opt (#318)
* fix: taosdump support ws timeout

* fix: free result when null

* test: add rust log for debug

* test: move rust debug as global

* test: disable verbose output

* test: verbose output

* fix: error output .github/workflows/3.0-taosdump-release.yml

* test: add taosa.log

* test: show taosws-rs commit

* fix: turn off rust log

* fix: enable taosadapter log to file

* fix: turn off verbose output

* fix: workflow name clearly

diff --git a/.github/workflows/3.0-taosdump-release.yml b/.github/workflows/3.0-taosdump-release.yml
--- a/.github/workflows/3.0-taosdump-release.yml
+++ b/.github/workflows/3.0-taosdump-release.yml
@@ -1,4 +1,4 @@
-name: CI (taosdump Release for 3.0)
+name: Ubuntu (3.0 taosdump native)
 
 on:
   push:
@@ -121,7 +121,7 @@ jobs:
 
           if find tools -name "taosdump*.py"|grep -q .;
           then
-            for i in `find tools -name "taosdump*.py"`; do python3 ./test.py -f $i > /dev/null 2&>1 && echo -e "\033[32m $i success! \033[0m" || echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
+            for i in `find tools -name "taosdump*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m" || echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
           fi
 
       - name: taosdump System Test
