test: split arm test

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -642,10 +642,10 @@ jobs:
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
-          #if find taosdump/ws3 -name "*.py"|grep -q .;
-          #then
-            #for i in `find taosdump/ws3 -name "*.py"|sort`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
-          #fi
+          if find taosdump/ws3 -name "*.py"|grep -q .;
+          then
+            for i in `find taosdump/ws3 -name "*.py"|sort`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+          fi
 
       - name: taosdump System Test cases
         if:
@@ -679,7 +679,7 @@ jobs:
 
           if find taosbenchmark -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark -name "*.py"|grep -Ev "websocket|taosdemo|kill-slow-query"|sort`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m $i success! \033[0m"|| echo -e " \033[31m $i failed! \033[0m"; done
+            for i in `find taosbenchmark -name "*.py"|grep -Ev "v2|websocket|taosdemo|kill-slow-query"|sort`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m $i success! \033[0m"|| echo -e " \033[31m $i failed! \033[0m"; done
           fi
 
       - name: taosBenchmakr WebSocket Test cases
@@ -692,7 +692,11 @@ jobs:
 
           if find taosbenchmark/ws -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark/ws -name "*.py"`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m $i success! \033[0m"|| echo -e " \033[31m $i failed! \033[0m" ;done
+            for i in `find taosbenchmark/ws -name "*.py"`;        \
+              do printf $i && python3 ./test.py -f $i > /dev/null \
+                && echo -e " \033[32m $i success! \033[0m"        \
+                || echo -e " \033[31m $i failed! \033[0m" ;       \
+                            done
           fi
 
       - name: taosdemo query Test
