test: move coverage to topdir

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -15,9 +15,8 @@ jobs:
 
     steps:
       - name: Run test for Coveralls report
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
-          submodules: recursive
           path: 'taos-tools'
           ref: 'develop'
 
@@ -69,7 +68,7 @@ jobs:
         with:
           repository: 'taosdata/TDengine'
           path: 'TDengine'
-          ref: 'feat/sangshuduo/TD-14141-update-taostools-for3.0'
+          ref: '3.0'
 
       - name: Change time zone
         if:
@@ -131,8 +130,8 @@ jobs:
           cd TDengine
           mkdir debug
           cd debug
-          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true -DTOOLS_COVER=true > /dev/null
-          make -j8 > /dev/null
+          cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DWEBSOCKET=true > /dev/null
+          make -j8 > /dev/null && make install > /dev/null
 
       - name: show TDengine's taosws commit
         if: |
@@ -149,26 +148,20 @@ jobs:
           || github.event_name == 'push'
         run: sudo apt-get install lzma-dev liblzma-dev libjansson-dev libz-dev libsnappy-dev pkg-config lcov expect -y > /dev/null
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Checkout taos-tools to PR number
         if: |
           github.event_name == 'pull_request' &&
           steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          cd TDengine/tools/taos-tools
+          cd ./taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
 
-      - name: Build & Install TDengine
-        if:
-          (steps.changed-files-specific.outputs.any_changed == 'true'
-          && github.event_name == 'pull_request')
-          || github.event_name == 'push'
-        run: |
-          cd TDengine
           mkdir debug ||:
           cd debug
+          cmake .. -DTOOLS_BUILD_TYPE=Release -DWEBSOCKET=true  -DTOOLS_COVER=true > /dev/null
           make -j8 > /dev/null
-          sudo make install > /dev/null
+          make install > /dev/null
           if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
           then
             echo "taos-tools build failure"
@@ -184,7 +177,7 @@ jobs:
           || github.event_name == 'push'
         run: |
           echo "TEST: taodump -p"
-          cd TDengine/tools/taos-tools/tests/taosdump
+          cd taos-tools/tests/taosdump
           ./exp.sh
 
       - name: Basic Test
@@ -193,7 +186,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: taosBenchmark --help"
           ./build/bin/taosBenchmark --help > /dev/null
           echo "TEST: taodump --help"
@@ -223,7 +216,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: simple and log database"
           ./build/bin/taosBenchmark -t 1 -n 1 -y
           ./build/bin/taosdump -D test -a
@@ -282,7 +275,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: epoch time and batch"
           ./build/bin/taosdump -D test -S 1500000000000 -E 1500000000004 -B 10 -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
@@ -297,7 +290,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: normal table"
           ./build/bin/taosBenchmark -N -t 2 -n 10 -y > /dev/null
           ./build/bin/taosdump -D test -gg > /dev/null
@@ -319,7 +312,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: -n escape_char"
           ./build/bin/taosdump -n -D test > /dev/null
           ./build/bin/taos -s "drop database test"
@@ -355,7 +348,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/debug
+          cd taos-tools/debug
           echo "TEST: dump old format data in"
           ./build/bin/taos -s "drop database test"
           tar xvJf ../tools/taos-tools/example-data/example-data.tar.xz -C .
@@ -368,14 +361,14 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/tests/pytest
+          cd taos-tools/tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
           echo "TEST: old cases"
-          python3 ./test.py -f tools/taosdumpTest.py > /dev/null
-          python3 ./test.py -f tools/taosdumpTest2.py > /dev/null
-          python3 ./test.py -f tools/taosdumpTestNanoSupport.py > /dev/null
+          python3 ./test.py -f taosdump/old/taosdumpTest.py > /dev/null
+          python3 ./test.py -f taosdump/old/taosdumpTest2.py > /dev/null
+          python3 ./test.py -f taosdump/old/taosdumpTestNanoSupport.py > /dev/null
           #python3 test.py -f query/nestedQuery/nestedQuery.py > /dev/null
           #python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null
 
@@ -385,7 +378,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/tools/taos-tools/tests
+          cd taos-tools/tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -402,7 +395,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/tools/taos-tools/tests
+          cd taos-tools/tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -411,33 +404,45 @@ jobs:
             for i in `find taosdump/ws3 -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
 
-      - name: System Test cases
+      - name: taosdump System Test cases
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/tests/system-test
+          cd taos-tools/tests
           echo "TEST: system test cases"
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          if find taosdump/system-test -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosdump -name "*.py"|grep -v taosdumpTestColTag`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosdump/system-test -name "*.py"|grep -v taosdumpTestColTag`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
-          python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"
+          python3 test.py -f taosdump/system-test/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"
 
+      - name: taosBenchmark Develop Test cases
+        if:
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          cd taos-tools/tests
           echo "TEST: taosdemo develop test cases"
-          cd ../develop-test
-          if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
+          if find taosbenchmark/develop-test -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosbenchmark/develop-test -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
+      - name: taosBenchmark System Test cases
+        if:
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          cd taos-tools/tests
           echo "TEST: taosdemo system test cases"
-          cd ../system-test
-          if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
+          if find taosbenchmark/system-test -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosbenchmark/system-test -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
       - name: Generate report
@@ -447,17 +452,17 @@ jobs:
           || github.event_name == 'push'
         run: |
           topdir=`pwd`
-          cd TDengine/debug/tools/taos-tools
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
-          gcov -abcfu ${topdir}/TDengine/tools/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
+          cd taos-tools/debug
+          gcov -abcfu ${topdir}/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
+          gcov -abcfu ${topdir}/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
           mkdir ${topdir}/coverage || :
           lcov -c -d . -o ${topdir}/coverage/lcov-with-deps.info
           lcov -r ${topdir}/coverage/lcov-with-deps.info "*/deps/*" -o ${topdir}/coverage/lcov.info
