test: add taosbenchmark cloud test case

diff --git a/.github/workflows/3.0-taosBenchmark-release.yml b/.github/workflows/3.0-taosBenchmark-release.yml
--- a/.github/workflows/3.0-taosBenchmark-release.yml
+++ b/.github/workflows/3.0-taosBenchmark-release.yml
@@ -154,7 +154,7 @@ jobs:
           pip3 install numpy fabric2 psutil pandas faker toml > /dev/null 2>&1
           pip3 install git+https://github.com/taosdata/taos-connector-python > /dev/null
 
-      - name: Test
+      - name: Test native cases
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -164,10 +164,23 @@ jobs:
 
           if find taosbenchmark -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark -name "*.py"|grep -Ev "websocket|taosdemo|kill-slow-query"|sort`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m taosbenchmark-release-test/$i success! \033[0m"|| echo -e " \033[31m taosbenchmark-release-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-release-failed.txt; done
+            for i in `find taosbenchmark -name "*.py"|grep -Ev "websocket|taosdemo|kill-slow-query|cloud"|sort`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m taosbenchmark-release-test/$i success! \033[0m"|| echo -e " \033[31m taosbenchmark-release-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-release-failed.txt; done
           fi
 
-      - name: Test WebSocket
+      - name: Test cloud cases
+        if:
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          cd tests
+
+          if find taosbenchmark -name "cloud*.py"|grep -q .;
+          then
+            for i in `find taosbenchmark -name "cloud*.py"`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m benchmark-cloud-test:$i success! \033[0m"|| echo -e " \033[31m benchmark-cloud-test:$i failed! \033[0m" | tee -a ~/benchmark-cloud-failed.txt; done
+          fi
+
+      - name: Test WebSocket cases
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -208,6 +221,11 @@ jobs:
         run: |
           if [ -f ~/taosbenchmark-release-failed.txt ];then
             cat ~/taosbenchmark-release-failed.txt
+            exit 1
+          fi
+
+          if [ -f ~/taosbenchmark-cloud-failed.txt ];then
+            cat ~/taosbenchmark-cloud-failed.txt
             exit 1
           fi
 
