fix: mute few warning print (#373)
* feat: taosdump support multiple directories

initial work to reduce buffer overflow

* fix: tune taosadapter log level to error

* fix: temporary disable double type case

* feat: refactor dump filename generation

* feat: add db dir and check if it exist

* feat: taosdump dump out to multiple directories

* feat: support dump in from multiple directories

* fix: build with websocket enabled

* test: enable error output

* fix: inpath buffer overflow

* fix: create db clause for db stb

* test: fix taosdump/native/taosdumpTestInspect.py

* fix: 3.0-coveralls.yml coveralls.yml

* feat: re-write dump subtable desc logic for cluster

* feat: add percent indicator for tbname fetch

* feat: fix debug print row

* feat: print to stderr

* feat: reuse stb desc for sub-tables

* feat: use directories tmp branch

* refactor: again

* feat: native dump out refactor

* refactor: ws impl

* refactor: ws done

* feat: fix unknown codec

* fix: unknown codec dump in

* test: check result in 3.0-coveralls.yml

* fix: unknown codec to dump normal table

* fix: add progress indicator 0

* fix: improve tag fetch

* fix: ntb get table des

* fix: tag value is null

* fix: dump db tb with unknown codec

* fix: unknown codec ntb/stb

* fix: revert codec specified

* fix: code cleanup

* chore: add info print macro

* feat: add errno check for thread_join

* fix: mute few warning pring

* fix: process value for v3

* test: add float and double to coverage test

* fix: process tag value for v3

* test: fix ws3 in ../.github/workflows/3.0-coveralls.yml

* fix: duration buffer

* fix: make 3.0.0.0 ver compatible first

* fix: reuse v2 way get tag value first to improve performance

* test: update workflow for taos-tools commit

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -69,7 +69,7 @@ jobs:
         with:
           repository: 'taosdata/TDengine'
           path: 'TDengine'
-          ref: '3.0'
+          ref: 'feat/sangshuduo/TD-14141-update-taostools-for3.0'
 
       - name: Change time zone
         if:
@@ -230,7 +230,7 @@ jobs:
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: complex columns"
-          ./build/bin/taosBenchmark -t 2 -n 10 -b bool,tinyint,smallint,int,bigint,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -A bool,tinyint,smallint,int,bigint,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -y > /dev/null
+          ./build/bin/taosBenchmark -t 2 -n 10 -b bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -A bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -y > /dev/null
 
           echo "TEST: whole db with null codec"
           ./build/bin/taosdump -D test -d null -gg > /dev/null
@@ -343,7 +343,7 @@ jobs:
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: complex with larger binary"
-          ./build/bin/taosBenchmark -t 2 -n 10 -w 40 -b bool,tinyint,smallint,int,bigint,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -A bool,tinyint,smallint,int,bigint,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -y > /dev/null
+          ./build/bin/taosBenchmark -t 2 -n 10 -w 40 -b bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -A bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -y > /dev/null
           ./build/bin/taosdump -D test -gg > /dev/null
           ./build/bin/taos -s "drop database test"
           ./build/bin/taosdump -i . -gg > /dev/null
@@ -408,7 +408,7 @@ jobs:
 
           if find taosdump/ws3 -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+            for i in `find taosdump/ws3 -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
 
       - name: System Test cases
