test: add ws3 test

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -356,17 +356,17 @@ jobs:
             for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
-          #      - name: taosdump WebSocket Develop Test
-          #if: steps.changed-files-specific.outputs.any_changed == 'true'
-          #run: |
-          #cd TDengine/tools/taos-tools/tests
-          #sudo pkill -9 taosadapter || :
-          #sudo pkill -9 taosd || :
+      - name: taosdump WebSocket Develop Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        run: |
+          cd TDengine/tools/taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
 
-          #if find taosdump/ws -name "*.py"|grep -q .;
-          #then
-          #  for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
-          #fi
+          if find taosdump/ws3 -name "*.py"|grep -q .;
+          then
+            for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+          fi
 
       - name: System Test cases
         if: steps.changed-files-specific.outputs.any_changed == 'true'
