fix: remove TDENGINE_3 macro dependency (#322)
* fix: remove TDENGINE_3 macro dependency

* fix: check for build in test workflow

* fix: reduce max dir len in taosdump

* fix: windows compile

diff --git a/.github/workflows/3.0-taosdump-release.yml b/.github/workflows/3.0-taosdump-release.yml
--- a/.github/workflows/3.0-taosdump-release.yml
+++ b/.github/workflows/3.0-taosdump-release.yml
@@ -112,6 +112,11 @@ jobs:
           mkdir debug ||:
           cd debug
           make -j8 > /dev/null && sudo make install > /dev/null
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
           pip3 install taospy numpy fabric2 psutil pandas faker toml > /dev/null
 
       - name: taosdump Func Test
diff --git a/.github/workflows/ci-taosBenchmark-debug.yml b/.github/workflows/ci-taosBenchmark-debug.yml
--- a/.github/workflows/ci-taosBenchmark-debug.yml
+++ b/.github/workflows/ci-taosBenchmark-debug.yml
@@ -101,6 +101,11 @@ jobs:
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
           cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZE=true -DBUILD_HTTP=false && make -j8 && sudo make install
 
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
           pip3 install taospy numpy fabric2 psutil pandas faker toml > /dev/null 2>&1
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
diff --git a/.github/workflows/ci-taosBenchmark-release-ws.yml b/.github/workflows/ci-taosBenchmark-release-ws.yml
--- a/.github/workflows/ci-taosBenchmark-release-ws.yml
+++ b/.github/workflows/ci-taosBenchmark-release-ws.yml
@@ -100,4 +100,9 @@ jobs:
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
           cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true && make -j8 && sudo make install
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
           pip3 install taospy numpy fabric2 psutil pandas faker toml > /dev/null 2>&1
diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -70,6 +70,11 @@ jobs:
           cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=true -DBUILD_TOOLS=true -DCOVER=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZER=true
           make > /dev/null
           sudo make install > /dev/null
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
 
       - name: Test
         run: |
