test: change 3.0-taosdump-release.yml to test stand aline taos-tools

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -59,7 +59,7 @@ jobs:
         run: |
           echo "One or more files listed above has changed."
 
-      - name: Checkout TDengine
+      - name: Checkout TDengine 3.0
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -119,7 +119,7 @@ jobs:
             TDengine/tools/taosws-rs/target/
           key: ${{ runner.os }}-cargo-target-${{ steps.setup-rust.outputs.rustc_hash }}
 
-      - name: cmake first TDengine
+      - name: first build TDengine 3.0
         if: |
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -409,17 +409,10 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          sleep 5
-
-          nohup taosadapter > /dev/null &
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
-
           cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
+          sleep 5
 
           echo "TEST: old cases"
           python3 ./test.py -f taosdump/old/taosdumpTest.py > /dev/null
@@ -434,20 +427,12 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
           sleep 5
 
-          nohup taosadapter > /dev/null &
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
-
-          cd tests
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-
           echo "TEST: develop test cases"
-
           if find taosdump/native -name "*.py"|grep -q .;
           then
             for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
@@ -486,20 +471,14 @@ jobs:
           sudo pkill -9 taosd || :
           sleep 5
 
-          nohup taosadapter > /dev/null &
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
-
           cd tests
           echo "TEST: system test cases"
           if find taosdump/system-test -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/system-test -name "*.py"|grep -v taosdumpTestColTag`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosdump/system-test -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
-          python3 test.py -f taosdump/system-test/TD-12478.py > /dev/null && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m"
-
-      - name: taosBenchmark Develop Test cases
+      - name: taosBenchmark Test cases
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -509,36 +488,63 @@ jobs:
           sudo pkill -9 taosd || :
           sleep 5
 
-          nohup taosadapter > /dev/null &
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
-
           cd tests
-          echo "TEST: taosdemo develop test cases"
-          if find taosbenchmark/develop-test -name "*.py"|grep -q .;
+          echo "TEST: taosBenchmark develop test cases"
+
+          if find taosbenchmark -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark/develop-test -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
-      - name: taosBenchmark System Test cases
+          if find taosbenchmark/ws -name "*.py"|grep -q .;
+          then
+            for i in `find taosbenchmark/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+          fi
+
+      - name: Checkout TDengine 2.6
+        if:
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        uses: actions/checkout@v2
+        with:
+          repository: 'taosdata/TDengine'
+          path: 'TDengine-develop'
+          ref: 'develop'
+
+      - name: build TDengine 2.6
+        if: |
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: |
+          whoami
+          cd TDengine-2.6
+          mkdir debug ||:
+          cd debug
+          cmake .. -DBUILD_HTTP=false > /dev/null
+          make -j8 > /dev/null && sudo rmtaos && sudo make install > /dev/null && cd .. && rm -rf debug
+          if [[ ! -f /usr/local/taos/bin/taosd ]] || [[ ! -f /usr/local/taos/bin/taosadapter ]]
+          then
+            echo "TDengine build failure"
+            exit 1
+          fi
+
+      - name: taosdump native Develop Test
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
           sleep 5
 
-          nohup taosadapter > /dev/null &
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
-
-          cd tests
-          echo "TEST: taosdemo system test cases"
-          if find taosbenchmark/system-test -name "*.py"|grep -q .;
+          echo "TEST: develop test cases"
+          if find taosdump/native -name "*.py"|grep -q .;
           then
-            for i in `find taosbenchmark/system-test -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
       - name: Generate report
diff --git a/.github/workflows/3.0-taosdump-release-ws.yml b/.github/workflows/3.0-taosdump-release-ws.yml
--- a/.github/workflows/3.0-taosdump-release-ws.yml
+++ b/.github/workflows/3.0-taosdump-release-ws.yml
@@ -75,14 +75,6 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #- name: Checkout TDengine with same branch of taos-tools
-          #run: |
-          #cd TDengine
-          #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
-          #git submodule update --init --recursive
-          #if: github.event_name == 'pull_request'
-
       - name: Set up Go
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
@@ -118,20 +110,22 @@ jobs:
             TDengine/tools/taosws-rs/target/
           key: ${{ runner.os }}-cargo-target-${{ steps.setup-rust.outputs.rustc_hash }}
 
-      - name: cmake first TDengine
+      - name: first build TDengine
         if: |
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          sudo apt update -y > /dev/null
-          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y > /dev/null
           cd TDengine
           mkdir debug
           cd debug
-          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true > /dev/null
-          make -j8 > /dev/null
-          sudo make install > /dev/null
+          cmake .. -DBUILD_HTTP=false -DWEBSOCKET=true > /dev/null
+          make -j8 > /dev/null && sudo make install > /dev/null && cd .. && rm -rf debug
+          if [[ ! -f /usr/local/taos/bin/taosd ]] || [[ ! -f /usr/local/taos/bin/taosadapter ]]
+          then
+            echo "TDengine build failure"
+            exit 1
+          fi
 
       - name: show TDengine's taosws commit
         if: |
@@ -141,29 +135,36 @@ jobs:
           cd TDengine/tools/taosws-rs
           git log --oneline | head -1
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Install packages for build taos-tools
+        if:
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
+        run: sudo apt-get install lzma-dev liblzma-dev libjansson-dev libz-dev libsnappy-dev pkg-config lcov expect -y > /dev/null
+
+      - name: Checkout taos-tools to PR number
         if: |
           github.event_name == 'pull_request' &&
           steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          cd TDengine/tools/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
 
-      - name: Build & Install TDengine
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine
           mkdir debug ||:
           cd debug
+          cmake .. -DTOOLS_BUILD_TYPE=Release -DWEBSOCKET=true > /dev/null
           make -j8 > /dev/null && sudo make install > /dev/null
-          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          if [[ ! -f /usr/local/taos/bin/taosdump ]] || [[ ! -f /usr/local/taos/bin/taosBenchmark ]]
           then
             echo "taos-tools build failure"
             exit 1
           fi
 
       - name: Install python packages
+        if: |
+          (steps.changed-files-specific.outputs.any_changed == 'true'
+          && github.event_name == 'pull_request')
+          || github.event_name == 'push'
         run: |
           pip3 install numpy fabric2 psutil pandas faker toml > /dev/null
           pip3 install git+https://github.com/taosdata/taos-connector-python > /dev/null
@@ -174,7 +175,7 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd TDengine/tools/taos-tools/tests
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -182,6 +183,8 @@ jobs:
           then
             for i in `find taosdump/ws3 -name "*.py"|grep -Ev "Float|Double"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m develop-test:$i success! \033[0m"|| echo -e "\033[31m develop-test:$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
+
+          for i in `find taosdump/ws3 -name "*.py" | grep "Float|Double"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
 
       - name: Check Test Result
         if:
diff --git a/.github/workflows/ci-taosBenchmark-release-ws.yml b/.github/workflows/ci-taosBenchmark-release-ws.yml
--- a/.github/workflows/ci-taosBenchmark-release-ws.yml
+++ b/.github/workflows/ci-taosBenchmark-release-ws.yml
@@ -1,4 +1,4 @@
-name: Ubuntu (2.x taosbenchmark WebSocket)
+name: Ubuntu (3.0 taosbenchmark WebSocket)
 
 on:
   push:
@@ -66,14 +66,6 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #- name: Checkout TDengine with same branch of taos-tools
-          #run: |
-          #cd TDengine
-          #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
-          #git submodule update --init --recursive
-          #if: github.event_name == 'pull_request'
-
       - name: Checkout TDengine's taos-tools to PR number
         if: |
           github.event_name == 'pull_request' &&
@@ -121,8 +113,12 @@ jobs:
       - name: Test
         run: |
           cd TDengine/tools/taos-tools/tests
-          for i in `find taosbenchmark/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m benchmark-ws-test:$i success! \033[0m"|| echo -e "\033[31m benchmark-ws-test:$i failed! \033[0m" | tee -a ~/benchmark-ws-failed.txt ;done
-      
+
+          if find taosbenchmark/ws -name "*.py"|grep -q .;
+          then
+            for i in `find taosbenchmark/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null && echo -e "\033[32m benchmark-ws-test:$i success! \033[0m"|| echo -e "\033[31m benchmark-ws-test:$i failed! \033[0m" | tee -a ~/benchmark-ws-failed.txt ;done
+          fi
+
       - name: Check Test Result
         run: |
           if [ -f ~/benchmark-ws-failed.txt ];then
