fix: refactor conn print

diff --git a/.github/workflows/3.0-taosBenchmark-debug.yml b/.github/workflows/3.0-taosBenchmark-debug.yml
--- a/.github/workflows/3.0-taosBenchmark-debug.yml
+++ b/.github/workflows/3.0-taosBenchmark-debug.yml
@@ -179,7 +179,7 @@ jobs:
 
           if find taosbenchmark/ -name "cloud*.py"|grep -q .;
           then
-            for i in `find taosbenchmark -name "cloud*.py"`; do printf $i && python3 ./test.py -f $i > /dev/null && echo -e " \033[32m benchmark-cloud-test:$i success! \033[0m"|| echo -e " \033[31m benchmark-cloud-test:$i failed! \033[0m" | tee -a ~/taosbenchmark-cloud-failed.txt; done
+            for i in `find taosbenchmark -name "cloud*.py"`; do printf $i && python3 ./test.py -f $i && echo -e " \033[32m benchmark-cloud-test:$i success! \033[0m"|| echo -e " \033[31m benchmark-cloud-test:$i failed! \033[0m" | tee -a ~/taosbenchmark-cloud-failed.txt; done
           fi
 
       - name: Test WebSocket cases
