test: check changed file in ../.github/workflows/centos-release.yml

diff --git a/.github/workflows/3.0-coveralls.yml b/.github/workflows/3.0-coveralls.yml
--- a/.github/workflows/3.0-coveralls.yml
+++ b/.github/workflows/3.0-coveralls.yml
@@ -125,13 +125,17 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          sudo apt update -y > /dev/null
-          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y > /dev/null
+          whoami
           cd TDengine
-          mkdir debug
+          mkdir debug ||:
           cd debug
           cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DWEBSOCKET=true > /dev/null
-          make -j8 > /dev/null && make install > /dev/null
+          make -j8 > /dev/null && sudo make install > /dev/null && cd .. && rm -rf debug
+          if [[ ! -f /usr/local/taos/bin/taosd ]] || [[ ! -f /usr/local/taos/bin/taosadapter ]]
+          then
+            echo "TDengine build failure"
+            exit 1
+          fi
 
       - name: show TDengine's taosws commit
         if: |
@@ -141,7 +145,7 @@ jobs:
           cd TDengine/tools/taosws-rs
           git log --oneline | head -1
 
-      - name: Install packages
+      - name: Install packages for build taos-tools
         if:
           (steps.changed-files-specific.outputs.any_changed == 'true'
           && github.event_name == 'pull_request')
@@ -159,8 +163,8 @@ jobs:
           mkdir debug ||:
           cd debug
           cmake .. -DTOOLS_BUILD_TYPE=Debug -DWEBSOCKET=true -DTOOLS_COVER=true > /dev/null
-          make -j8 > /dev/null && make install > /dev/null
-          if [[ ! -f /usr/local/taos/bin/taosdump ]] && [[ ! -f /usr/local/taos/bin/taosBenchmark ]]
+          make -j8 > /dev/null && sudo make install > /dev/null
+          if [[ ! -f /usr/local/taos/bin/taosdump ]] || [[ ! -f /usr/local/taos/bin/taosBenchmark ]]
           then
             echo "taos-tools build failure"
             exit 1
@@ -175,7 +179,7 @@ jobs:
           || github.event_name == 'push'
         run: |
           echo "TEST: taodump -p"
-          cd taos-tools/tests/taosdump
+          cd tests/taosdump
           ./exp.sh
 
       - name: Basic Test
@@ -184,7 +188,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: taosBenchmark --help"
           ./build/bin/taosBenchmark --help > /dev/null
           echo "TEST: taodump --help"
@@ -204,8 +216,6 @@ jobs:
           echo "TEST: taodump --databases -h localhost -u root"
           ./build/bin/taosdump --databases -h localhost -u root > /dev/null 2>&1 || :
 
-          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
-          sleep 10
 
           # test codec
       - name: taosdump codec Test
@@ -214,7 +224,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: simple and log database"
           ./build/bin/taosBenchmark -t 1 -n 1 -y
           ./build/bin/taosdump -D test -a
@@ -225,45 +243,45 @@ jobs:
 
           echo "TEST: whole db with null codec"
           ./build/bin/taosdump -D test -d null -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d null -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: whole db with snappy codec"
           ./build/bin/taosdump -D test -d snappy -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d snappy -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: whole db with deflate codec"
           ./build/bin/taosdump -D test -d deflate -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d deflate -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: whole db with lzma codec"
           ./build/bin/taosdump -D test -d lzma -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d lzma -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: whole db with unknown codec"
           ./build/bin/taosBenchmark -t 2 -n 2 -y > /dev/null
           ./build/bin/taosdump -D test -d unknown -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d unknown -gg > /dev/null
-          ./build/bin/taos -s "select count(*) from test.meters"|grep "4 |" && echo success || exit 1
+          taos -s "select count(*) from test.meters"|grep "4 |" && echo success || exit 1
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: singal normal table with unknown codec"
           ./build/bin/taosdump test d0 -d unknown -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d unknown -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: unknown codec"
           ./build/bin/taosdump -D test -d unknown -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -d unknown -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
@@ -273,7 +291,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: epoch time and batch"
           ./build/bin/taosdump -D test -S 1500000000000 -E 1500000000004 -B 10 -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
@@ -288,18 +314,26 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: normal table"
           ./build/bin/taosBenchmark -N -t 2 -n 10 -y > /dev/null
           ./build/bin/taosdump -D test -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: singla normal table"
           ./build/bin/taosBenchmark -t 2 -n 2 -y > /dev/null
           ./build/bin/taosdump test d0 > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -gg > /dev/null
           taos -s "select count(tbname) from test.meters" | grep "1 row" || exit 1
           rm -rf *.sql *.avro* taosdump.*
@@ -310,33 +344,41 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: -n escape_char"
           ./build/bin/taosdump -n -D test > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -n -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: escaped tag"
-          ./build/bin/taos -s "drop database test"
-          ./build/bin/taos -s "create database test"
-          ./build/bin/taos -s "create stable stb (ts timestamp, \`N\` int) tags(`T` int)"
-          ./build/bin/taos -s "insert into test.tb using test.stb tags(0) values(now, 0)"
+          taos -s "drop database test"
+          taos -s "create database test"
+          taos -s "create stable stb (ts timestamp, \`N\` int) tags(`T` int)"
+          taos -s "insert into test.tb using test.stb tags(0) values(now, 0)"
           ./build/bin/taosdump -D test > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -n -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: -L loose_mode"
           ./build/bin/taosdump -L -D test > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -L -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
           echo "TEST: complex with larger binary"
           ./build/bin/taosBenchmark -t 2 -n 10 -w 40 -b bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -A bool,tinyint,smallint,int,bigint,float,double,utinyint,usmallint,uint,ubigint,binary,nchar,timestamp -y > /dev/null
           ./build/bin/taosdump -D test -gg > /dev/null
-          ./build/bin/taos -s "drop database test"
+          taos -s "drop database test"
           ./build/bin/taosdump -i . -gg > /dev/null
           rm -rf *.sql *.avro* taosdump.*
 
@@ -346,10 +388,18 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/debug
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd debug
           echo "TEST: dump old format data in"
-          ./build/bin/taos -s "drop database test"
-          tar xvJf ../tools/taos-tools/example-data/example-data.tar.xz -C .
+          taos -s "drop database test"
+          tar xvJf ../example-data/example-data.tar.xz -C .
           ./build/bin/taosdump -i dump -gg
           rm -rf *.sql *.avro* taosdump.*
 
@@ -359,7 +409,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -376,7 +434,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -393,7 +459,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -408,7 +482,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           echo "TEST: system test cases"
           if find taosdump/system-test -name "*.py"|grep -q .;
           then
@@ -423,7 +505,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           echo "TEST: taosdemo develop test cases"
           if find taosbenchmark/develop-test -name "*.py"|grep -q .;
           then
@@ -436,7 +526,15 @@ jobs:
           && github.event_name == 'pull_request')
           || github.event_name == 'push'
         run: |
-          cd taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+          sleep 5
+
+          nohup taosadapter > /dev/null &
+          nohup sudo TAOS_SUPPORT_VNODES=256 taosd > /dev/null &
+          sleep 10
+
+          cd tests
           echo "TEST: taosdemo system test cases"
           if find taosbenchmark/system-test -name "*.py"|grep -q .;
           then
@@ -450,7 +548,7 @@ jobs:
           || github.event_name == 'push'
         run: |
           topdir=`pwd`
-          cd taos-tools/debug
+          cd debug
           gcov -abcfu ${topdir}/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
           gcov -abcfu ${topdir}/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
           gcov -abcfu ${topdir}/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
