fix: revert to 1.1.8 to fix centos bug

diff --git a/.github/workflows/centos-release.yml b/.github/workflows/centos-release.yml
--- a/.github/workflows/centos-release.yml
+++ b/.github/workflows/centos-release.yml
@@ -76,16 +76,22 @@ jobs:
       - name: Build & Install TDengine
         run: |
           yum install -y python3 python3-pip zlib-devel xz-devel snappy-devel jansson jansson-devel pkgconfig libatomic libstdc++-static openssl-devel > /dev/null
-          python3 -m pip install --upgrade pip
+          python3 -m pip install --upgrade pip > /dev/null 2>&1
           cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true && make -j8 && make install
-          pip3 install taospy numpy fabric2 psutil pandas faker
+          pip3 install taospy numpy fabric2 psutil pandas faker > /dev/null 2>&1
 
-      - name: Old Test cases
+      - name: taosdump Old Test cases
         run: |
           cd TDengine/tests/pytest
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
+          pkill -9 taosadapter || :
+          pkill -9 taosd || :
 
           echo "TEST: old cases"
-          python3 ./test.py -f tools/taosdumpTest.py
-          python3 ./test.py -f tools/taosdumpTest2.py
+          python3 ./test.py -f tools/taosdumpTest.py && echo -e "\033[32m pytest/tools/taosdumpTest.py success! \033[0m" || echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt
+
+      - name: Check Test Result
+        run: |
+          if [ -f ~/taosdump-failed.txt ];then
+            cat ~/taosdump-failed.txt;
+            exit 1;
+          fi
