fix: windows compile

diff --git a/.github/workflows/centos-release.yml b/.github/workflows/centos-release.yml
--- a/.github/workflows/centos-release.yml
+++ b/.github/workflows/centos-release.yml
@@ -74,6 +74,11 @@ jobs:
           yum install -y python3 python3-pip zlib-devel xz-devel snappy-devel jansson jansson-devel pkgconfig libatomic libstdc++-static openssl-devel > /dev/null
           python3 -m pip install --upgrade pip > /dev/null 2>&1
           cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true && make -j8 && make install
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
           pip3 install taospy numpy fabric2 psutil pandas faker toml > /dev/null 2>&1
 
       - name: taosdump Old Test cases
diff --git a/.github/workflows/coveralls.yml b/.github/workflows/coveralls.yml
--- a/.github/workflows/coveralls.yml
+++ b/.github/workflows/coveralls.yml
@@ -127,6 +127,11 @@ jobs:
           cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DWEBSOCKET=true -DBUILD_TOOLS=true -DCOVER=true -DTOOLS_BUILD_TYPE=Debug > /dev/null 2>&1
           make > /dev/null 2>&1
           sudo make install > /dev/null
+          if [[ ! -f /usr/bin/taosdump ]] && [[ ! -f /usr/bin/taosBenchmark ]]
+          then
+            echo "taos-tools build failure"
+            exit 1
+          fi
           pip3 install taospy numpy fabric2 psutil pandas faker toml > /dev/null
 
       - name: exp Test
