fix: github actions func test (#288)
* [TD-12333]<fix>: func test missed

* add submodules

* submodule recursive

* adjust dependencies installation timing

* stop taosd for func test

and modify subtask description

* exit 0 if pkill non-exist process

* pip3 install taospy

* add more taosdump test cases

* make checkout taos-tools for PR only

* test: improve workflow speed

* fix: split ci to taosdump and taosbenchmark

* test: add tj-actions/changed-files to actions

diff --git a/.github/workflows/ci-taosBenchmark-debug.yml b/.github/workflows/ci-taosBenchmark-debug.yml
--- a/.github/workflows/ci-taosBenchmark-debug.yml
+++ b/.github/workflows/ci-taosBenchmark-debug.yml
@@ -1,4 +1,4 @@
-name: CI (Release)
+name: CI (taosBenchmark Debug)
 
 on:
   push:
@@ -7,7 +7,7 @@ on:
     branches: [ develop ]
 
 env:
-  TOOLS_BUILD_TYPE: Release
+  TOOLS_BUILD_TYPE: Debug
   PR_NUMBER: ${{ github.event.number }}
 
 jobs:
@@ -24,7 +24,36 @@ jobs:
           BASE_BRANCH: ${{ github.base_ref }}
         if: github.event_name == 'pull_request'
 
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v23.2
+
+      - name: List all changed files
+        run: |
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            echo "$file was changed"
+          done
+
+      - name: Get specific changed files
+        id: changed-files-specific
+        uses: tj-actions/changed-files@v23.2
+        with:
+          files: |
+            src/bench*
+            inc/*
+            .github/workflows/*
+
+      - name: Run step if any of the listed files above change
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        run: |
+          echo "One or more files listed above has changed."
+
       - name: Checkout tdengine
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         uses: actions/checkout@v2
         with:
           submodules: recursive
@@ -33,6 +62,7 @@ jobs:
           ref: 'develop'
 
       - name: Change time zone
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
@@ -41,12 +71,18 @@ jobs:
           #run: |
           #cd TDengine
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
-          #git submodule update --init --recursive
+          #git branch -a | grep -w ${{ github.head_ref }} \
+          #  && git checkout ${{ github.head_ref }} \
+          #  && rm -rf tests \
+          #  && git submodule update --init --recursive --force \
+          #  || echo "${{ github.head_ref }} not found in TDengine"
+
           #if: github.event_name == 'pull_request'
 
       - name: Checkout TDengine's taos-tools to PR number
-        if: github.event_name == 'pull_request'
+        if: |
+          steps.changed-files-specific.outputs.any_changed == 'true' &&
+          github.event_name == 'pull_request'
         run: |
           cd TDengine/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
@@ -54,37 +90,25 @@ jobs:
           git submodule update --init --recursive
 
       - name: Set up Go
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         uses: actions/setup-go@v2
         with:
           go-version: 1.14
 
       - name: Build & Install TDengine
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
-          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false && make -j8 && sudo make install
+          cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZE=true -DBUILD_HTTP=false && make -j8 && sudo make install
 
-      - name: Func Test
-        run: |
-          cd TDengine/tests/pytest
           pip3 install taospy numpy fabric2 psutil pandas faker
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
-          python3 ./test.py -f tools/taosdumpTest.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTest2.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTest3.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTestNanoSupport.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-
-      - name: System Test
+      - name: taosBenchmark System Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-          then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
-          fi
-
           if [ -d 5-taos-tools/taosbenchmark ];
           then
             if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
@@ -93,45 +117,32 @@ jobs:
             fi
           fi
 
-      - name: Old Test for taodump
-        run: |
-          cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
-
-      - name: Old Test for taodemo
+      - name: taosBenchmark Old Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/tests/pytest
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
           python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null 2>&1 && echo -e "\033[32m TD-5213/insertSigcolumnsNum4096.py success! \033[0m"|| echo -e "\033[31m TD-5213/insertSigcolumnsNum4096.py failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt
 
-      - name: Develop Test
+      - name: taosBenchmark Develop Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/tests/develop-test
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-          then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
-          fi
-
           if [ -d 5-taos-tools/taosbenchmark ];
           then
             if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
             then
-              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt; done
+              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt; done
             fi
           fi
 
       - name: Check Test Result
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          if [ -f ~/taosdump-failed.txt ];then
-            cat ~/taosdump-failed.txt;
-            exit 1;
-          fi
           if [ -f ~/taosbenchmark-failed.txt ];then
             cat ~/taosbenchmark-failed.txt;
             exit 1;
