fix: taosdump ws float null

diff --git a/.github/workflows/ci-taosdump-release-ws.yml b/.github/workflows/ci-taosdump-release-ws.yml
--- a/.github/workflows/ci-taosdump-release-ws.yml
+++ b/.github/workflows/ci-taosdump-release-ws.yml
@@ -1,4 +1,4 @@
-name: CI (taosdump Debug)
+name: CI - WebSocket (Release)
 
 on:
   push:
@@ -7,7 +7,7 @@ on:
     branches: [ develop ]
 
 env:
-  TOOLS_BUILD_TYPE: Debug
+  TOOLS_BUILD_TYPE: Release
   PR_NUMBER: ${{ github.event.number }}
 
 jobs:
@@ -44,7 +44,7 @@ jobs:
         with:
           files: |
             src/taosdump*
-            tests/taosdump*
+            tests/taosdump/ws/*
             inc/*
             .github/workflows/*
 
@@ -60,9 +60,10 @@ jobs:
           submodules: recursive
           repository: 'taosdata/TDengine'
           path: 'TDengine'
-          ref: 'develop'
+          ref: 'chore/sangshuduo/TD-15140-libtaos-ws-submodule'
 
       - name: Change time zone
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
@@ -71,18 +72,14 @@ jobs:
           #run: |
           #cd TDengine
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} \
-          #  && git checkout ${{ github.head_ref }} \
-          #  && rm -rf tests \
-          #  && git submodule update --init --recursive --force \
-          #  || echo "${{ github.head_ref }} not found in TDengine"
-
+          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
+          #git submodule update --init --recursive
           #if: github.event_name == 'pull_request'
 
       - name: Checkout TDengine's taos-tools to PR number
         if: |
-          steps.changed-files-specific.outputs.any_changed == 'true' &&
-          github.event_name == 'pull_request'
+          github.event_name == 'pull_request' &&
+          steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
@@ -95,43 +92,18 @@ jobs:
         with:
           go-version: 1.14
 
+      - name: Set up Rust
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+
       - name: Build & Install TDengine
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
-          cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZE=true -DBUILD_HTTP=false && make -j8 && sudo make install
-
+          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false -DWEBSOCKET=true && make -j8 && sudo make install
           pip3 install taospy numpy fabric2 psutil pandas faker
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-
-      - name: taosdump Func Test
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/tests/pytest
-          python3 ./test.py -f tools/taosdumpTest.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTest2.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTest3.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-          python3 ./test.py -f tools/taosdumpTestNanoSupport.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
-
-      - name: taosdump System Test
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-          then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
-          fi
-
-      - name: taosdump Old Test
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-          cd TDengine/tests/system-test
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
 
       - name: taosdump Develop Test
         if: steps.changed-files-specific.outputs.any_changed == 'true'
@@ -140,9 +112,9 @@ jobs:
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
-          if find taosdump/native -name "*.py"|grep -q .;
+          if find taosdump/ws -name "*.py"|grep -q .;
           then
-            for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
+            for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
 
       - name: Check Test Result
diff --git a/.github/workflows/coveralls.yml b/.github/workflows/coveralls.yml
--- a/.github/workflows/coveralls.yml
+++ b/.github/workflows/coveralls.yml
@@ -292,11 +292,15 @@ jobs:
       - name: Develop Test cases
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
-          cd TDengine/tests/develop-test
+          cd TDengine/src/kit/taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+
           echo "TEST: develop test cases"
-          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+
+          if find taosdump/native -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+            for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
           fi
 
       - name: System Test cases
