fix: split ci to taosdump and taosbenchmark

diff --git a/.github/workflows/ci-taosdump-debug.yml b/.github/workflows/ci-taosdump-debug.yml
--- a/.github/workflows/ci-taosdump-debug.yml
+++ b/.github/workflows/ci-taosdump-debug.yml
@@ -1,13 +1,15 @@
-name: CI (Release)
+name: CI (taosdump Debug)
 
 on:
   push:
     branches: [ develop ]
   pull_request:
     branches: [ develop ]
+    paths-ignore:
+      - 'src/bench**'
 
 env:
-  TOOLS_BUILD_TYPE: Release
+  TOOLS_BUILD_TYPE: Debug
   PR_NUMBER: ${{ github.event.number }}
 
 jobs:
@@ -41,8 +43,12 @@ jobs:
           #run: |
           #cd TDengine
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
-          #git submodule update --init --recursive
+          #git branch -a | grep -w ${{ github.head_ref }} \
+          #  && git checkout ${{ github.head_ref }} \
+          #  && rm -rf tests \
+          #  && git submodule update --init --recursive --force \
+          #  || echo "${{ github.head_ref }} not found in TDengine"
+
           #if: github.event_name == 'pull_request'
 
       - name: Checkout TDengine's taos-tools to PR number
@@ -61,21 +67,21 @@ jobs:
       - name: Build & Install TDengine
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
-          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Release -DBUILD_HTTP=false && make -j8 && sudo make install
+          cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZE=true -DBUILD_HTTP=false && make -j8 && sudo make install
 
-      - name: Func Test
-        run: |
-          cd TDengine/tests/pytest
           pip3 install taospy numpy fabric2 psutil pandas faker
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
+      - name: taosdump Func Test
+        run: |
+          cd TDengine/tests/pytest
           python3 ./test.py -f tools/taosdumpTest.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
           python3 ./test.py -f tools/taosdumpTest2.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
           python3 ./test.py -f tools/taosdumpTest3.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
           python3 ./test.py -f tools/taosdumpTestNanoSupport.py > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt
 
-      - name: System Test
+      - name: taosdump System Test
         run: |
           cd TDengine/tests/system-test
           sudo pkill -9 taosadapter || :
@@ -85,29 +91,14 @@ jobs:
             for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt; done
           fi
 
-          if [ -d 5-taos-tools/taosbenchmark ];
-          then
-            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
-            then
-              for i in `find 5-taos-tools/taosbenchmark -name "*.py" | grep -v taosdemoTestQueryWithJson`; do sleep 1 && python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m system-test/$i success! \033[0m"|| echo -e "\033[31m system-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt; done
-            fi
-          fi
-
-      - name: Old Test for taodump
+      - name: taosdump Old Test
         run: |
           cd TDengine/tests/system-test
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
           python3 test.py -f 5-taos-tools/TD-12478.py > /dev/null 2>&1 && echo -e "\033[32m  system-test/5-taos-tools/TD-12478.py success! \033[0m"|| echo -e "\033[31m system-test/5-taos-tools/TD-12478.py failed! \033[0m" | tee -a ~/taosdump-failed.txt
 
-      - name: Old Test for taodemo
-        run: |
-          cd TDengine/tests/pytest
-          sudo pkill -9 taosadapter || :
-          sudo pkill -9 taosd || :
-          python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null 2>&1 && echo -e "\033[32m TD-5213/insertSigcolumnsNum4096.py success! \033[0m"|| echo -e "\033[31m TD-5213/insertSigcolumnsNum4096.py failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt
-
-      - name: Develop Test
+      - name: taosdump Develop Test
         run: |
           cd TDengine/tests/develop-test
           sudo pkill -9 taosadapter || :
@@ -115,24 +106,12 @@ jobs:
 
           if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
           then
-            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
-          fi
-
-          if [ -d 5-taos-tools/taosbenchmark ];
-          then
-            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
-            then
-              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosbenchmark-failed.txt; done
-            fi
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
 
       - name: Check Test Result
         run: |
           if [ -f ~/taosdump-failed.txt ];then
             cat ~/taosdump-failed.txt;
-            exit 1;
-          fi
-          if [ -f ~/taosbenchmark-failed.txt ];then
-            cat ~/taosbenchmark-failed.txt;
             exit 1;
           fi
