[TD-12434]<fix>: taosdump null nchar/binary length (#56)
* [TD-12434]<fix>: taosdump null nchar/binary length

* fix cmake workflow

* fix cmake/codecov workflow

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -56,7 +56,7 @@ jobs:
       - name: Func Test
         run: |
           cd TDengine/tests/pytest
-          pip3 install taospy numpy fabric2 psutil pandas
+          pip3 install taospy numpy fabric2 psutil pandas faker
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -64,4 +64,14 @@ jobs:
           python3 ./test.py -f tools/taosdumpTest2.py
           python3 ./test.py -f tools/taosdumpTest3.py
           python3 ./test.py -f tools/taosdumpTestNanoSupport.py
+
+      - name: System Test
+        run: |
+          cd TDengine/tests/system-test
+          for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m success! \033[0m"|| echo -e "\033[31m failed! \033[0m" ;done
+
+      - name: Develop Test
+        run: |
+          cd TDengine/tests/develop-test
+          for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m success! \033[0m"|| echo -e "\033[31m failed! \033[0m" ;done
 
diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -51,7 +51,7 @@ jobs:
           cd src/kit/taos-tools/
           ctest --verbose
           cd ../../../../tests/pytest
-          pip3 install taospy numpy fabric2 psutil pandas
+          pip3 install taospy numpy fabric2 psutil pandas faker
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -59,6 +59,18 @@ jobs:
           python3 ./test.py -f tools/taosdumpTest2.py
           python3 ./test.py -f tools/taosdumpTest3.py
           python3 ./test.py -f tools/taosdumpTestNanoSupport.py
+
+          cd ../develop-test
+          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          then
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m success! \033[0m"|| echo -e "\033[31m failed! \033[0m" ;done
+          fi
+
+          cd ../system-test
+          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          then
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m success! \033[0m"|| echo -e "\033[31m failed! \033[0m" ;done
+          fi
 
       - name: Generate report
         run: |
