update yml

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -100,20 +100,19 @@ jobs:
       - name: Develop Test
         run: |
           cd TDengine/tests/develop-test
-          python3 ./test.py -f 5-taos-tools/taosbenchmark/auto_create_table_json.py
           
-#          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-#          then
-#            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt ;done
-#          fi
-#
-#          if [ -d 5-taos-tools/taosbenchmark ];
-#          then
-#            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
-#            then
-#              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
-#            fi
-#          fi
+          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          then
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt ;done
+          fi
 
-#          [ -f taosdump-failed.txt ] && [ ! -s taosdump-failed.txt ] && exit 1
-#          [ -f taosbenchmark-failed.txt ] && [ ! -s taosbenchmark-failed.txt ] && exit 1
+          if [ -d 5-taos-tools/taosbenchmark ];
+          then
+            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
+            then
+              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
+            fi
+          fi
+
+          [ -f taosdump-failed.txt ] && [ ! -s taosdump-failed.txt ] && exit 1
+          [ -f taosbenchmark-failed.txt ] && [ ! -s taosbenchmark-failed.txt ] && exit 1
