update ci

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -15,12 +15,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      #      - name: Checkout taos-tools
-      #        uses: actions/checkout@v2
-      #        with:
-      #          ref: develop
-      #          submodules: recursive
-      #          path: 'taos-tools'
+      - name: Checkout taos-tools
+        uses: actions/checkout@v2
+        with:
+          ref: develop
+          submodules: recursive
+          path: 'taos-tools'
 
       - name: Step that prints name of pull request's base branch
         run: |
@@ -69,62 +69,49 @@ jobs:
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
           cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DBUILD_TYPE=Debug -DBUILD_HTTP=false && make && sudo make install
 
-      - name: step 1
-        run: nohup sudo taosadapter &
+      - name: Func Test
+        run: |
+          cd TDengine/tests/pytest
+          pip3 install taospy numpy fabric2 psutil pandas faker
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
 
-      - name: step 1
-        run: nohup sudo taosd &
+          python3 ./test.py -f tools/taosdumpTest.py
+          python3 ./test.py -f tools/taosdumpTest2.py
+          python3 ./test.py -f tools/taosdumpTest3.py
+          python3 ./test.py -f tools/taosdumpTestNanoSupport.py
 
-      - name: step 1
-        run: "curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'show databases;' 127.0.0.1:6041/rest/sql"
-          #      - name: Func Test
-          #        run: |
-          #          cd TDengine/tests/pytest
-          #          pip3 install taospy numpy fabric2 psutil pandas faker
-          #          sudo pkill -9 taosadapter || :
-          #          sudo pkill -9 taosd || :
-          #          nohup taosadapter &
-          #          nohup taosd &
-          #          curl -H 'Authorization: Basic cm9vdDp0YW9zZGF0YQ==' -d 'show databases;' 127.0.0.1:6041/rest/sql
+      - name: System Test
+        run: |
+          cd TDengine/tests/system-test
+          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          then
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt; done
+          fi
 
+          if [ -d 5-taos-tools/taosbenchmark ];
+          then
+            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
+            then
+              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
+            fi
+          fi
 
-          #          python3 ./test.py -f tools/taosdumpTest.py
-          #          python3 ./test.py -f tools/taosdumpTest2.py
-          #          python3 ./test.py -f tools/taosdumpTest3.py
-          #          python3 ./test.py -f tools/taosdumpTestNanoSupport.py
+      - name: Develop Test
+        run: |
+          cd TDengine/tests/develop-test
+          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
+          then
+            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt ;done
+          fi
 
-#
-#      - name: System Test
-#        run: |
-#          cd TDengine/tests/system-test
-#          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-#          then
-#            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt; done
-#          fi
-#
-#          if [ -d 5-taos-tools/taosbenchmark ];
-#          then
-#            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
-#            then
-#              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
-#            fi
-#          fi
-#
-#      - name: Develop Test
-#        run: |
-#          cd TDengine/tests/develop-test
-#          if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
-#          then
-#            for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt ;done
-#          fi
-#
-#          if [ -d 5-taos-tools/taosbenchmark ];
-#          then
-#            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
-#            then
-#              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
-#            fi
-#          fi
-#
-#          #[ -f taosdump-failed.txt ] && [ ! -s taosdump-failed.txt ] && exit 1
-#          #[ -f taosbenchmark-failed.txt ] && [ ! -s taosbenchmark-failed.txt ] && exit 1
+          if [ -d 5-taos-tools/taosbenchmark ];
+          then
+            if find 5-taos-tools/taosbenchmark -name "*.py"|grep -q .;
+            then
+              for i in `find 5-taos-tools/taosbenchmark -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosbenchmark-failed.txt; done
+            fi
+          fi
+
+          [ -f taosdump-failed.txt ] && [ ! -s taosdump-failed.txt ] && exit 1
+          [ -f taosbenchmark-failed.txt ] && [ ! -s taosbenchmark-failed.txt ] && exit 1
