add same logic in codecov

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -14,11 +14,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Run test for codecov report
+        uses: actions/checkout@v2
         with:
           submodules: recursive
           path: 'taos-tools'
           ref: 'develop'
+
+      - name: Step that prints name of pull request's base branch
+        run: |
+          echo "Pull request's base branch is: ${BASE_BRANCH}"
+          echo "Pull request's branch is: ${GITHUB_REF##*/}"
+          echo "Pull request's head ref is: ${GITHUB_HEAD_REF}"
+        env:
+          BASE_BRANCH: ${{ github.base_ref }}
+        if: github.event_name == 'pull_request'
 
       - name: Checkout tdengine
         uses: actions/checkout@v2
@@ -32,6 +42,14 @@ jobs:
         run: |
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
+
+      - name: Checkout TDengine with same branch of taos-tools
+        run: |
+          cd TDengine
+          git pull
+          git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
+          git submodule update --init --recursive
+        if: github.event_name == 'pull_request'
 
       - name: Install packages
         run: sudo apt-get install lzma-dev libjansson-dev libsnappy-dev
