test: coveralls.yml includes websocket test

diff --git a/.github/workflows/coveralls.yml b/.github/workflows/coveralls.yml
--- a/.github/workflows/coveralls.yml
+++ b/.github/workflows/coveralls.yml
@@ -113,15 +113,22 @@ jobs:
         with:
           go-version: 1.14
 
+      - name: Set up Rust
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+
       - name: Build & Install TDengine
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine
           mkdir debug
           cd debug
-          cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DBUILD_TOOLS=true -DCOVER=true -DTOOLS_BUILD_TYPE=Debug -DTOOLS_SANITIZE=true > /dev/null 2>&1
+          cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DWEBSOCKET=true -DBUILD_TOOLS=true -DCOVER=true -DTOOLS_BUILD_TYPE=Debug > /dev/null 2>&1
           make > /dev/null 2>&1
           sudo make install > /dev/null
+          pip3 install taospy numpy fabric2 psutil pandas faker > /dev/null
 
       - name: Basic Test
         if: steps.changed-files-specific.outputs.any_changed == 'true'
@@ -277,7 +284,6 @@ jobs:
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/tests/pytest
-          pip3 install taospy numpy fabric2 psutil pandas faker > /dev/null
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
 
@@ -289,7 +295,7 @@ jobs:
           python3 test.py -f query/nestedQuery/nestedQuery.py > /dev/null
           python3 test.py -f tools/taosdemoAllTest/TD-5213/insertSigcolumnsNum4096.py > /dev/null
 
-      - name: Develop Test cases
+      - name: taosdump native Develop Test
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           cd TDengine/src/kit/taos-tools/tests
@@ -301,6 +307,18 @@ jobs:
           if find taosdump/native -name "*.py"|grep -q .;
           then
             for i in `find taosdump/native -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" ;done
+          fi
+
+      - name: taosdump WebSocket Develop Test
+        if: steps.changed-files-specific.outputs.any_changed == 'true'
+        run: |
+          cd TDengine/src/kit/taos-tools/tests
+          sudo pkill -9 taosadapter || :
+          sudo pkill -9 taosd || :
+
+          if find taosdump/ws -name "*.py"|grep -q .;
+          then
+            for i in `find taosdump/ws -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m develop-test/$i success! \033[0m"|| echo -e "\033[31m develop-test/$i failed! \033[0m" | tee -a ~/taosdump-failed.txt ;done
           fi
 
       - name: System Test cases
